image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm --version
    - npm run generate
  artifacts:
    paths:
      - public
  only:
    - master

